version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    groups:
      spring:
        patterns: ["org.springframework*", "io.spring*"]
      victools:
        patterns: ["com.github.victools*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
